### ISSUE TITLE
[BUG] -  Content Component as Angular element - produces the error - properties of undefined (reading 'data-ck-expando')

### ISSUE THREAD

**Issue by dinbtechit** [formio/angular#1004]
## Environment
Angular version - 15.2.0

- Hosting type
  - [] Form.io
  - [X ] Local deployment
    - Version: 
- Formio.js version: 
```
    "@formio/angular": "^5.5.0-rc.11",
    "@formio/js": "^5.0.0-rc.27",
```
- Frontend framework:
- Browser: Chrome
- Browser version: latest

## Steps to Reproduce
1. Create an angular element - with formio.
2.  Build the project to generate the javascript and css file and include it in a HTML file.
3.  open HTML file and try to add content component to the form. Due to the ckeditor the following error occurs. (see video more details.)

```
sfs-form-designer-element.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'data-ck-expando')
    at dr (emittermixin.js:256:9)
    at Eu._getProxyEmitter (emittermixin.js:112:39)
    at Eu.stopListening (emittermixin.js:86:23)
    at Eu.destroy (view.js:492:8)
    at viewcollection.js:89:26
    at Array.map (<anonymous>)
    at dl.map (collection.js:334:22)
    at dl.destroy (viewcollection.js:89:8)
    at dl.detachFromDom (bodycollection.js:94:9)
    at Gl.destroy (editoruiview.js:52:13)
```
> Note the above error occurs only if you export formio as an Angular Element. Regular angular projects work fine.
## Expected behavior

Content component should work as expected.

## Observed behavior

https://github.com/formio/angular/assets/17984781/b6a90082-5390-48b8-90fb-85224233d653

**Comment by lane-formio** [comment]
Can you try this with some of the more recent versions?
The versions below in particular are compatible with the 5.x version of formio/js
@formio/angular: 6.5.0 || 7.5.0-rc.2 || 8.0.0-rc.5

**Comment by lane-formio** [comment]
<div>Agent Lane Doughtie linked Freshdesk ticket <a href="https://formhelp.freshdesk.com/a/tickets/46510">46510</a> for this issue.</div><br/>
