### ISSUE TITLE
[Question] implementation of FormBuilder give "Cannot read properties of null"

### ISSUE THREAD

**Issue by Ludovic1974** [formio/angular#1022]
I have a problem with the implementation of FormBuilder.
I have adapted the form builder as indicated in the GIT section described at https://github.com/formio/angular/wiki/Form-Builder and I am getting the following error:

core.mjs:7739 ERROR TypeError: Cannot read properties of null (reading '0')
    at new Formio (Formio.js:144:19)
    at FormBuilder.setForm (Form.js:185:22)
    at new Form (Form.js:99:13)
    at FormBuilder._createSuperInternal (FormBuilder.js:35:283)
    at new FormBuilder (FormBuilder.js:50:19)
    at BuilderComponent.ngOnInit (builder.component.ts:23:18)
    at callHook (core.mjs:2551:22)
    at callHooks (core.mjs:2520:17)
    at executeInitAndCheckHooks (core.mjs:2471:9)
    at refreshView (core.mjs:9595:21)

Has anyone else experienced this? How could it be resolved?

**Comment by MiguiTE** [comment]
Happens to me too

**Comment by lane-formio** [comment]
<div>Agent Jeriah Henley linked Freshdesk ticket <a href="https://formhelp.freshdesk.com/a/tickets/51948">51948</a> for this issue.</div><br/>

**Comment by lane-formio** [comment]
Is this still happening in our latest versions?
