### ISSUE TITLE
Gulp build stopped with error "ngc' errored after 42 ms"

### ISSUE THREAD

**Issue by abdullahqudeer** [formio/angular#343]
## Environment
Windows , angular-formio  

- Hosting type
  - [x] Form.io
  - [x] Local deployment
    - Version: 
- Formio.js version: formio.js-4.0.0-rc.25
- angular-formio version : angular-formio-4.0.0-beta.9
- Frontend framework: angular

## Steps to Reproduce
1. simply download source code 
2.  npm install
3. gulp build

## Expected behavior

build should be compiled.

## Observed behavior
ngc' errored after 42 ms

below is complete detail.
  
[15:02:45] Starting 'build'...
[15:02:45] Starting 'clean'...
[15:02:45] Starting 'clean:dist'...
[15:02:45] Starting 'clean:tmp'...
[15:02:45] Starting 'clean:build'...
[15:02:45] Finished 'clean:tmp' after 10 ms
[15:02:45] Finished 'clean:build' after 13 ms
[15:02:45] Finished 'clean:dist' after 17 ms
[15:02:45] Finished 'clean' after 22 ms
[15:02:45] Starting 'compile'...
[15:02:45] Starting 'clean:dist'...
[15:02:45] Finished 'clean:dist' after 3.11 ms
[15:02:45] Starting 'copy:source'...
[15:02:46] Finished 'copy:source' after 651 ms
[15:02:46] Starting 'styles-formio'...
[15:02:46] Starting 'styles-builder'...
[15:02:46] Starting 'formio-css'...
[15:02:46] Starting 'builder-css'...
[15:02:47] Finished 'formio-css' after 686 ms
[15:02:47] Finished 'builder-css' after 688 ms
[15:02:47] Finished 'styles-formio' after 693 ms
[15:02:47] Finished 'styles-builder' after 694 ms
[15:02:47] Starting 'inline-resources'...
[15:02:47] Finished 'inline-resources' after 171 ms
[15:02:47] Starting 'ngc'...
[15:02:47] Starting 'ngc-angular'...
[15:02:47] Starting 'ngc-auth'...
[15:02:47] Starting 'ngc-auth-angular'...
[15:02:47] Starting 'ngc-manager'...
[15:02:47] Starting 'ngc-manager-angular'...
[15:02:47] Starting 'ngc-grid'...
[15:02:47] Starting 'ngc-grid-angular'...
[15:02:47] Starting 'ngc-resource'...
[15:02:47] Starting 'ngc-resource-angular'...
[15:02:47] 'ngc' errored after 42 ms
[15:02:47] Error: spawn ngc ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
[15:02:47] 'compile' errored after 1.58 s
[15:02:47] 'build' errored after 1.61 s
[15:02:47] The following tasks did not complete: ngc-angular, ngc-auth, ngc-auth-angular, ngc-manager, ngc-manager-angular, ngc-grid, ngc-grid-angular, ngc-resource, ngc-resource-angular
[15:02:47] Did you forget to signal async completion?

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
