### ISSUE TITLE
ReferenceError: navigator is not defined

### ISSUE THREAD

**Issue by kenobi-io** [formio/angular#386]
ReferenceError: navigator is not defined
    at eval (webpack:///./node_modules/popper.js/dist/esm/popper.js?:31:20)
    at Module../node_modules/popper.js/dist/esm/popper.js (angular-universal-starter/prerender.js:11499:1)
    at __webpack_require__ (angular-universal-starter/prerender.js:20:30)
    at eval (webpack:///./node_modules/tooltip.js/dist/esm/tooltip.js?:2:67)
    at Module../node_modules/tooltip.js/dist/esm/tooltip.js (angular-universal-starter/prerender.js:14088:1)
    at __webpack_require__ (angular-universal-starter/prerender.js:20:30)
    at eval (webpack:///./node_modules/formiojs/components/_classes/component/Component.js?:58:39)
    at Object../node_modules/formiojs/components/_classes/component/Component.js (angular-universal-starter/prerender.js:3936:1)
    at __webpack_require__ (angular-universal-starter/prerender.js:20:30)
    at eval (webpack:///./node_modules/angular-material-formio/fesm5/angular-material-formio.js?:49:108)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! universal-demo@7.0.0 generate:prerender: `node prerender.js`
npm ERR! Exit status 1

**Comment by travist** [comment]
Another browser issue.... What environment are you running this renderer?

**Comment by odobdober** [comment]
angular universal https://github.com/Angular-RU/angular-universal-starter

**Comment by aiwebb** [comment]
@odobdober, that sounds like it may be an error from a node environment - is that correct? We don't currently support server-side rendering.

**Comment by Sidiro23** [comment]
We're currently addressing a backlog of GitHub issues, and as part of this effort, some inactive issues may be marked as closed. This isn't a dismissal, but a step toward more efficient tracking.

If you feel the issue is still relevant, please re-open and we'll ensure it gets the attention it deserves. Your understanding is appreciated as we work to enhance our open-source responsiveness.
