### ISSUE TITLE
Angular Universal support

### ISSUE THREAD

**Issue by ghost** [formio/angular#441]
## Environment
Please provide as many details as you can:

- Hosting type
  - [] Form.io
  - [X] Local deployment
    - Version: 
- Formio.js version: 4.4.3
- Frontend framework: Angular 7 + Angular Universal
- Browser: N/A
- Browser version: N/A

## Steps to Reproduce
1. Install Formio 4.4.3
2. Run Angular Universal build and serve scripts.

## Expected behavior
Formio module should be exported without errors.

## Observed behavior
It seems the file produced by tsickle at `node_modules/angular-formio/components/formio/formio.component.js` has errors. These errors are preventing me from starting my application. 

### Output
`/Users/username/folder/node_modules/angular-formio/components/formio/formio.component.js:19
import { Component, Optional, ViewEncapsulation, NgZone } from '@angular/core';
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/username/folder/dist/server.js:9705:18)
    at __webpack_require__ (/Users/username/folder/dist/server.js:20:30)
    at Object.KAm/ (/Users/username/folder/dist/server.js:9476:18)`

**Comment by travist** [comment]
This may have to do with Angular Universal. This renderer has not been tested in that environment, so this may turn into a request to make Angular Formio work with Angular Universal as a feature request.

**Comment by orentoga** [comment]
Is there a solution soon?

**Comment by travist** [comment]
We are not working on a solution for this. We are hopeful that the community could help with this endeavor.
