### ISSUE TITLE
[BUG] Failed to load formio.component.html in Jest test

### ISSUE THREAD

**Issue by michealharrington** [formio/angular#747]
## Environment
Please provide as many details as you can:

- Hosting type
  - [ ] Form.io
  - [x] Local deployment
    - Version: 5.0.2
- Formio.js version: 4.12.7
- Frontend framework: Angular 11.2.4
- Browser:
- Browser version:

## Steps to Reproduce
1. import { FormioModule } from '@formio/angular'; 
2. expect(component).toBeTruthy();
3. Test fails

## Expected behavior
Test passes
## Observed behavior
Test failure
Stacktrace:
```
Uncaught (in promise): Failed to load formio.component.html

      at resolvePromise (node_modules/zone.js/dist/zone.js:832:39)
      at resolvePromise (node_modules/zone.js/dist/zone.js:784:21)
      at node_modules/zone.js/dist/zone.js:894:21
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (node_modules/zone.js/dist/zone.js:421:35)
      at AsyncTestZoneSpec.Object.<anonymous>.AsyncTestZoneSpec.onInvokeTask (node_modules/zone.js/dist/async-test.js:86:33)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvokeTask (node_modules/zone.js/dist/proxy.js:145:43)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invokeTask (node_modules/zone.js/dist/zone.js:420:40)
      at Zone.Object.<anonymous>.Zone.runTask (node_modules/zone.js/dist/zone.js:188:51)
      at drainMicroTaskQueue (node_modules/zone.js/dist/zone.js:601:39)
      at ZoneTask.Object.<anonymous>.ZoneTask.invokeTask [as invoke] (node_modules/zone.js/dist/zone.js:507:25)
      at invokeTask (node_modules/zone.js/dist/zone.js:1671:18)
      at XMLHttpRequest.globalZoneAwareCallback (node_modules/zone.js/dist/zone.js:1708:25)
      at XMLHttpRequest.callTheUserObjectsOperation (node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:318:25)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at XMLHttpRequestImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at fireAnEvent (node_modules/jsdom/lib/jsdom/living/helpers/events.js:18:36)
      at Request.<anonymous> (node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:889:5)
      at Gunzip.<anonymous> (node_modules/request/request.js:1076:12)
```

## Example
Trying to write a test for a component that has a formio component.

For code or form JSON, please enclose in a code block:

```js
beforeEach(
        waitForAsync(() => {
            TestBed.configureTestingModule({
                declarations: [
                    SlamCrudFormComponent,
                ],
                imports: [
                    FormioModule,
                ],
            }).compileComponents().then(() => {
                fixture = TestBed.createComponent(SlamCrudFormComponent);
                component = fixture.componentInstance;
            });
        })
    );
```

**Comment by michealharrington** [comment]
Update:
Adding `CommonModule` to the imports, change the error to:
`Uncaught (in promise): Failed to load formio.alerts.component.html`

**Comment by wag110894** [comment]
Hello @michealharrington, are you still experiencing this issue? If so,  can you try upgrading to the latest version of angular and see if you can still replicate the issue? The latest version of Angular is 5.2.2

**Comment by michealharrington** [comment]
My co-worker recently went through an updated all our formio versions and everything seems to be working now. We are running 5.2.2 now.
